# additional data require to create the Docker image
packaging:
  # files to add to the build, usually used with ADD in the Dockerfile
  add:
    - target/${project.build.finalName}.jar
# optional list of port to expose on the host
ports:
  - 8080
# containers that this should be linked to, started before this one and stopped afterwards
links:
  - db
healthChecks:
  pings:
    - url: http://localhost:8080
      timeout: 60000
# tag to use for images
tag: jolokia/${project.artifactId}-alexec:${project.version}